[project]
name = "python-best-practices"
version = "0.0.1"
description = "A collection of Python best practices and patterns"
authors = ["Theo Leuthardt"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []